version: '3.9'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=your_neon_db_url
      - TMDB_API_KEY=your_tmdb_api_key
      - JWT_SECRET=your_jwt_secret
